import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#2F4F4F',
    flex: 1,
  },
  centerContent: {
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  splashImage: {
    width: 172,
    height: 172,
  },
  splashText: {
    color: '#fff',
    fontSize: 24,
    margin: 10,
  },
  splashIndicator: {
    marginTop: 56,
  },
  getStartedImage: {
    width: 260,
  },
  getStartedText: {
    color: '#fff',
    fontSize: 24,
    marginTop: 20,
  },
  getStartedDesc: {
    color: '#fff',
    fontSize: 12,
  },
  getStartedButton: {
    marginTop: 76,
  },
  button: {
    height: 48,
    width: 223,
    backgroundColor: '#FF685C',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
  },
  buttonText: {
    fontSize: 14,
    color: '#fff',
    textAlign: 'center',
  },
  authContainer: {
    backgroundColor: '#FCFCFC',
    flex: 1,
  },
  authContent: {
    margin: 24,
  },
  title: {
    fontSize: 16,
    color: '#373639',
    textAlign: 'center',
    marginTop: 100,
    marginBottom: 30,
    fontWeight: '600',
  },
  input: {
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 6,
    paddingHorizontal: 16,
    shadowColor: 'black',
    shadowOpacity: 0.1,
    elevation: 7,
  },
  buttonBlue: {
    backgroundColor: '#384DFE',
    borderRadius: 6,
    height: 48,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  authText: {
    color: '#373639',
  },
  authTextGrey: {
    color: '#B0B0B0',
    textAlign: 'center',
  },
  bold: {
    fontWeight: 'bold',
  },
  inputGroup: {
    marginVertical: 12,
  },
  authTitle: {
    fontSize: 24,
    color: '#373639',
    fontWeight: 'bold',
    marginVertical: 12,
  },
  textGrey: {
    color: '#B0B0B0',
  },
  textLink: {
    color: 'blue',
    fontWeight: 'bold',
  },
  headerIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    marginRight: 12,
  },
  headerBar: {
    flexDirection: 'row',
    paddingVertical: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#373639',
  },
  homeContent: {
    marginHorizontal: 16,
    flex: 1,
  },
  searchBar: {
    backgroundColor: '#fff',
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    shadowColor: 'black',
    shadowOpacity: 0.1,
    elevation: 7,
  },
  homeTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#373639',
  },
  todo: {
    backgroundColor: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
    shadowColor: '#999999',
    shadowOpacity: 0.7,
    elevation: 7,
  },
  todoIcon: {
    margin: 4,
  },
  floatingButton: {
    backgroundColor: '#43b05c',
    height: 48,
    width: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 32,
    right: 32,
    shadowColor: 'black',
    shadowOpacity: 0.7,
    elevation: 64,
  },
  fbButton: {
    height: 48,
    backgroundColor: '#36589E',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    flex: 1,
    flexDirection: 'row',
  },
  googleButton: {
    height: 48,
    backgroundColor: '#EB4132',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    flex: 1,
    flexDirection: 'row',
    marginLeft: 4,
  },
  drawerStyle: {
    backgroundColor: '#2F4F4F',
    padding: 28,
    flex: 1,
    justifyContent: 'space-evenly',
  },
  drawerTitle: {
    color: 'white',
    fontSize: 20,
    fontWeight: '600',
  },
  drawerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  drawerIcon: {
    tintColor: '#fff',
    height: 28,
    width: 28,
    marginRight: 8,
  },
  drawerText: {
    fontSize: 16,
    color: '#fff',
  },
  drawerDesc: {
    opacity: 0.5,
    fontSize: 14,
    color: 'white',
  },
  drawerImage: {
    width: 95,
    height: 95,
    alignSelf: 'center',
    marginBottom: 20,
  },
  followers: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  drawerButton: {
    padding: 8,
    backgroundColor: 'white',
    borderRadius: 20,
  },
  lineSocialButton: {
    backgroundColor: '#B0B0B0',
    flex: 1,
    height: 2,
    margin: 8,
  },
});
